export const CONST_PathRequest = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  ORDERS_CREATE: 'ORDERS_CREATE',
  ORDERS_ALL: 'ORDERS_ALL',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_DELETE: 'ORDER_DELETE',
  ORDER_HISTORRICAL: 'ORDER_HISTORRICAL',
  FILTER: 'FILTER'
}
